final List<Map<String, dynamic>> travelPlaces = [
  {
    "name": "Manarola, Italy",
    "cardImage": "assets/images/manarola_card.jpg", // Card
    "detailImage": "assets/images/manarola_details.jpg", // Detail
    "rating": 4.5,
    "cost": 770,
    "city": "Manarola",
    "country": "Italy",
    "Type": "Mountain",
  },
  {
    "name": "Zermatt, Switzerland",
    "cardImage": "assets/images/zermatt_card.jpg",
    "detailImage": "assets/images/zermatt_details.jpg",
    "rating": 4.7,
    "cost": 850,
    "city": "Zermatt",
    "country": "Switzerland",
    "Type": "Mountain",
  },
  {
    "name": "Santorini, Greece",
    "cardImage": "assets/images/Santorini_card.jpg",
    "detailImage": "assets/images/Santorini_details.jpg",
    "rating": 4.6,
    "cost": 690,
    "city": "Santorini",
    "country": "Greece",
    "Type": "Forest",
  },
  {
    "name": "Kyoto, Japan",
    "cardImage": "assets/images/kyoto_card.jpg",
    "detailImage": "assets/images/kyoto_details.jpg",
    "rating": 4.8,
    "cost": 820,
    "city": "Kyoto",
    "country": "Japan",
    "Type": "Forest",
  },
  {
    "name": "Cappadocia, Turkey",
    "cardImage": "assets/images/Cappadocia_card.jpg",
    "detailImage": "assets/images/Cappadocia_details.jpg",
    "rating": 4.6,
    "cost": 750,
    "city": "Cappadocia",
    "country": "Turkey",
    "Type": "Mountain",
  },
  {
    "name": "Bali, Indonesia",
    "cardImage": "assets/images/Bali_card.jpg",
    "detailImage": "assets/images/Bali_details.jpg",
    "rating": 4.9,
    "cost": 680,
    "city": "Bali",
    "country": "Indonesia",
    "Type": "Desert",
  },
];
